### ISSUE TITLE
In order to submit a Symfony Form, either handleRequest() or submit() should be called (not both)

### ISSUE THREAD

**Issue by paza** [libgraviton/graviton#161]
**Where:**
https://github.com/libgraviton/graviton/blob/develop/src/Graviton/RestBundle/Controller/RestController.php#L592

**Definition:**
submit(): Used to manually submit a form (e.g. HTTP method has to be checked manually)
handleRequest(): Handles the form submission automatically (e.g. HTTP method is checked automatically)

see http://symfony.com/doc/current/cookbook/form/direct_submit.html

**Wrong:**
```
// ...
$form->handleRequest($request);
$form->submit(json_decode(str_replace('"$ref"', '"ref"', $request->getContent()), true), false);
// ...
```
Actually, I think Symfony should throw an Exception when calling submit() after handleRequest() was called.

**Correct:**
```
// ...
$form->submit(json_decode(str_replace('"$ref"', '"ref"', $request->getContent()), true), false);
// ...
```

**Comment by hairmare** [comment]
This might be an artefact from me hacking on it. I think I remember having tried some combos in that method until all my tests where green... This shouldn't be hard to fix but we'll need to find time to look into it.

As it seems symfony doesn't throw the mentioned exception ;)
