### ISSUE TITLE
$ref searches in arrays use .. operator while non $ref searches use . operator

### ISSUE THREAD

**Issue by q-src** [libgraviton/graviton#253]
I need to get all file resources having a specific $ref within their links array. However, the following request does always return an empty result:

<http://graviton-develop.nova.scapp.io/file/?eq(links.%24ref,%2Fcore%2Fapp%2Fadmin)>

Same for <http://graviton-develop.nova.scapp.io/file/?like(links.%24ref,\*)>.

But when you execute <http://graviton-develop.nova.scapp.io/file/?eq(links.type,user)>, you'll see that these requests should return at least one result.

Do I send wrong requests or is there a bug affecting filtering by $ref within array?

**Comment by hairmare** [comment]
@q-src In the first example your the link should be fully qualified.

http://graviton-develop.nova.scapp.io/file/?eq(links.%24ref,http%3A%2F%2Fgraviton%2Ddevelop.nova.scapp.io%2Fcore%2Fapp%2Fadmin)

While this still doesn't work, I'm pretty sure that it did work at some time in the past. So it does look like this is a regression.

**Comment by q-src** [comment]
@hairmare Thanks for the reply.

I've tried it not fully qualified because this works for filtering by $refs which are not within an array. For example:
http://graviton-develop.nova.scapp.io/core/module/?eq(app.%24ref,%2Fcore%2Fapp%2Fadmin)

Moreover, the request works with `..` syntax:
http://graviton-develop.nova.scapp.io/file/?eq(links..%24ref,%2Fcore%2Fapp%2Fadmin)

However, this is no consistent behaviour because http://graviton-develop.nova.scapp.io/file/?eq(links..type,user) does return an empty result.

In addition, the following behaviours concerning filtering by array might interest you too: http://graviton-develop.nova.scapp.io/file/?like(links,*) does return an empty result and http://graviton-develop.nova.scapp.io/file/?like(links..%24ref,*) fails with HTTP 500 and response `null`.

**Comment by hairmare** [comment]
The last point you raise is is also in https://github.com/xiag-ag/rql-parser/issues/1. There certainly also are issues with $ref behaviour not always matching non $ref behaviour, looks like something smelly is going on there.

**Comment by narcoticfresh** [comment]
So old, close..
